M48
; DRILL file {KiCad (6.0.6-0)} date Wednesday, August 03, 2022 at 09:40:11 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-03T09:40:11-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0940
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1400
%
G90
G05
T1
X3.9961Y-2.75
X4.2639Y-2.75
T2
X5.5632Y-5.6582
T3
X4.1852Y-5.3352
T0
M30
