M48
; DRILL file {KiCad (6.0.6)} date Thu 04 Aug 2022 11:16:23 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-04T23:16:23-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0940
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1400
%
G90
G05
T1
X3.9961Y-2.75
X4.2639Y-2.75
T2
X5.5632Y-5.6582
T3
X4.1852Y-5.3352
T0
M30
